### PR TITLE
CircleCI: fix resource_class

### PR DESCRIPTION
**Pull request by syntrust**
Need to specify the machine name to resource_class when using `machine: true`, otherwise, it will use a container that has no required dependencies.

### CODE REVIEW

**Review by qzhodl — APPROVED** [review]

**Review by blockchaindevsh — COMMENTED** [review]
Where is `swc/ax101` defined?

**Comment by syntrust** [comment]
> Where is `swc/ax101` defined?

Just copy & paste. @qzhodl ?

**Comment by pochenai** [comment]
> > Where is `swc/ax101` defined?
> 
> Just copy & paste. @qzhodl ?

Yes, I've tried. Then, we're good to go.

**Comment by blockchaindevsh** [comment]
> > Where is `swc/ax101` defined?
> 
> Just copy & paste. @qzhodl ?

I guess it's defined in the circle ci backend. We can go through it on Saturday.

**Comment by qzhodl** [comment]
> > Where is `swc/ax101` defined?
> 
> Just copy & paste. @qzhodl ?

Yes, that's the name of our self-hosted runner

**Pull request merged**
