### PR TITLE
Fix `go_test_all`

### PR DESCRIPTION
**Pull request by blockchaindevsh**
This PR fixes the tests mentioned [here](https://github.com/ethstorage/optimism/issues/109).

The alt-da test failure is caused by the extra `FetchReceipts` call in [`getTxSucceed`](https://github.com/ethstorage/optimism/blob/cb15c77e100b991446f7a6f9180f913da812f6ce/op-node/rollup/derive/blob_data_source.go#L77).

### CODE REVIEW

**Review by qizhou — APPROVED** [review]

**Comment by qzhodl** [comment]
> This PR fixes the tests mentioned [here](https://github.com/ethstorage/optimism/issues/109).
> 
> The alt-da test failure is caused by the extra `FetchReceipts` call in [`getTxSucceed`](https://github.com/ethstorage/optimism/blob/cb15c77e100b991446f7a6f9180f913da812f6ce/op-node/rollup/derive/blob_data_source.go#L77).

Should we enable `go_test_all` in circleci now since the issue has been fixed?

**Comment by blockchaindevsh** [comment]
> Should we enable `go_test_all` in circleci now since the issue has been fixed?

This job depends on `contracts-bedrock-build`, maybe it can only be enabled after https://github.com/ethstorage/optimism/issues/111 is fixed?

**Comment by qzhodl** [comment]
> > Should we enable `go_test_all` in circleci now since the issue has been fixed?
> 
> This job depends on `contracts-bedrock-build`, maybe it can only be enabled after #111 is fixed?

I believe it depends on `contracts-bedrock-build` rather than `contracts-bedrock-checks`

**Comment by blockchaindevsh** [comment]
> I believe it depends on `contracts-bedrock-build` rather than `contracts-bedrock-checks`

Turned on in 6f1f11582a871296dd4e68e82d288d976279ab02, but seems not triggered,  is there anything I'm missing to trigger it?

**Comment by qzhodl** [comment]
> > I believe it depends on `contracts-bedrock-build` rather than `contracts-bedrock-checks`
> 
> Turned on in [6f1f115](https://github.com/ethstorage/optimism/commit/6f1f11582a871296dd4e68e82d288d976279ab02), but seems not triggered, is there anything I'm missing to trigger ci?

I deleted the trigger in circleci settings to prevent the CI from running on every commit. Team members can now manually trigger it on the [web page](https://app.circleci.com/pipelines/circleci/VJoJbnHRXJiFR13mWFvRfZ/SHyYDZiLFYMtveJSZVFKbw)

**Review by qzhodl — APPROVED** [review]

**Pull request merged**
