### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by blockchaindevsh**
This PR merges monorepo commit 718b9b018dd821.

### CODE REVIEW

**Review by qizhou — APPROVED** [review]

**Comment by qzhodl** [comment]
I’m a bit curious about how we picked the upstream commit https://github.com/ethstorage/optimism/commit/718b9b018dd821b0bd205df5c6d02ac7dbbba77d, Was it related to a specific release version of the OP Stack [here](https://github.com/ethereum-optimism/optimism/releases)

**Comment by blockchaindevsh** [comment]
> I’m a bit curious about how we picked the upstream commit [718b9b0](https://github.com/ethstorage/optimism/commit/718b9b018dd821b0bd205df5c6d02ac7dbbba77d), Was it related to a specific release version of the OP Stack [here](https://github.com/ethereum-optimism/optimism/releases)

It was the tip of the upstream's develop branch at the beginning of merge.

**Comment by qzhodl** [comment]
> > I’m a bit curious about how we picked the upstream commit [718b9b0](https://github.com/ethstorage/optimism/commit/718b9b018dd821b0bd205df5c6d02ac7dbbba77d), Was it related to a specific release version of the OP Stack [here](https://github.com/ethereum-optimism/optimism/releases)
> 
> It was the tip of the upstream's develop branch at the beginning of merge.

Should we pick a specific release version to merge? I noticed that op-geth follows this method in practice [here](https://github.com/ethereum-optimism/op-geth/issues/387)

**Comment by blockchaindevsh** [comment]
> Should we pick a specific release version to merge? I noticed that op-geth follows this method in practice [here](https://github.com/ethereum-optimism/op-geth/issues/387)

We'll merge with Holocene version when it's released. Before that, we'll just merge the latest code.

**Comment by qzhodl** [comment]
> > Should we pick a specific release version to merge? I noticed that op-geth follows this method in practice [here](https://github.com/ethereum-optimism/op-geth/issues/387)
> 
> We'll merge with Holocene version when it's released. Before that, we'll just merge the latest code.

The OP team releases minor versions quite frequently, as shown in the [link](https://github.com/ethereum-optimism/optimism/releases), where both OP Stack v1.9.3 and v1.9.2 were released in September. I would suggest merging a specific release version for better code stability.

**Comment by blockchaindevsh** [comment]
> The OP team releases minor versions quite frequently, as shown in the [link](https://github.com/ethereum-optimism/optimism/releases), where both OP Stack v1.9.3 and v1.9.2 were released in September. I would suggest merging a specific release version for better code stability.

We can merge a release version in a separate PR, which will be small. But based on previous experience, the code quality of develop branch is also quite good.

**Review by qzhodl — APPROVED** [review]

**Comment by qizhou** [comment]
> > The OP team releases minor versions quite frequently, as shown in the [link](https://github.com/ethereum-optimism/optimism/releases), where both OP Stack v1.9.3 and v1.9.2 were released in September. I would suggest merging a specific release version for better code stability.
> 
> We can merge a release version in a separate PR, which will be small. But based on previous experience, the code quality of develop branch is also quite good.

The tests (e.g., CI) sometimes fail at develop branch (as I experienced these days) so I think the recent release may be good merge point.

**Comment by blockchaindevsh** [comment]
> > > The OP team releases minor versions quite frequently, as shown in the [link](https://github.com/ethereum-optimism/optimism/releases), where both OP Stack v1.9.3 and v1.9.2 were released in September. I would suggest merging a specific release version for better code stability.
> > 
> > 
> > We can merge a release version in a separate PR, which will be small. But based on previous experience, the code quality of develop branch is also quite good.
> 
> The tests (e.g., CI) sometimes fail at develop branch (as I experienced these days) so I think the recent release may be good merge point.

When we're ready to deploy the next testnet, I'll ensure to merge with latest release version(hopefully when Holocene version is released).

As this PR is already very big, the most important thing for this PR is to ensure our own logic remains in the correct places.

**Review by qizhou — APPROVED** [review]

**Review by pochenai — APPROVED** [review]

**Pull request merged**
