### PR TITLE
CircleCI: fix go-tests / DencunBlobTx

### PR DESCRIPTION
**Pull request by syntrust**
The test cases that were supposed to reject blob tx should now accept it.

Error [log](https://app.circleci.com/pipelines/circleci/VJoJbnHRXJiFR13mWFvRfZ/SHyYDZiLFYMtveJSZVFKbw/75/workflows/8c45fb9a-d059-4580-94b5-b9869f515abe/jobs/1465)

```
=== RUN   TestDencunBlobTxInclusion
=== PAUSE TestDencunBlobTxInclusion
=== CONT  TestDencunBlobTxInclusion
    e2e.go:104: Running test. Assigned executor (0) matches current executor (0) of total (1)
    sequencer.go:663:           INFO [12-19|04:21:22.398] Starting sequencing, without known pre-state role=sequencer
    sequencer.go:685:           INFO [12-19|04:21:22.398] Sequencer has been started               role=sequencer "next action"=2024-12-19T04:21:22+0000
    state.go:398:               DEBUG[12-19|04:21:22.398] Sync process step                        role=sequencer
    clsync.go:107:              DEBUG[12-19|04:21:22.398] CL sync received forkchoice update       role=sequencer unsafe=000000..000000:0 safe=000000..000000:0 finalized=000000..000000:0
    status.go:66:               DEBUG[12-19|04:21:22.398] Forkchoice update                        role=sequencer unsafe=000000..000000:0 safe=000000..000000:0 finalized=000000..000000:0
    sequencer.go:457:           DEBUG[12-19|04:21:22.400] Sequencer is processing forkchoice update role=sequencer unsafe=000000..000000:0 latest=000000..000000:0
    state.go:390:               WARN [12-19|04:21:22.400] Deriver system is resetting              role=sequencer err="reset: cannot continue derivation until Engine has been reset"
    l2_verifier.go:355:         WARN [12-19|04:21:22.400] Derivation pipeline is being reset       role=sequencer err="reset: cannot continue derivation until Engine has been reset"
    sequencer.go:436:           ERROR[12-19|04:21:22.400] Sequencer encountered reset signal, aborting work role=sequencer err="reset: cannot continue derivation until Engine has been reset"
    sequencer.go:166:           DEBUG[12-19|04:21:22.400] Sequencer action schedule changed        role=sequencer time=2024-12-19T04:21:22+0000 wait=-2.077697ms ok=false event=reset-event
    start.go:121:               INFO [12-19|04:21:22.401] Loaded current L2 heads                  role=sequencer unsafe=f27875..efed49:0 safe=f27875..efed49:0 finalized=f27875..efed49:0 unsafe_origin=65615c..4c99cd:0 safe_origin=65615c..4c99cd:0
    start.go:181:               INFO [12-19|04:21:22.402] Walking back L1Block by number           role=sequencer curr=65615c..4c99cd:0 next=65615c..4c99cd:0 l2block=f27875..efed49:0
    start.go:240:               INFO [12-19|04:21:22.402] Hit finalized L2 head, returning immediately role=sequencer unsafe=f27875..efed49:0 safe=f27875..efed49:0 finalized=f27875..efed49:0 unsafe_origin=65615c..4c99cd:0 safe_origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.402] Sync process step                        role=sequencer
    chain_spec.go:191:          INFO [12-19|04:21:22.402] Current hardfork version detected        role=sequencer forkName=granite
    sequencer.go:453:           INFO [12-19|04:21:22.402] Engine reset confirmed, sequencer may continue role=sequencer next=true
    sequencer.go:166:           DEBUG[12-19|04:21:22.403] Sequencer action schedule changed        role=sequencer time=2024-12-19T04:21:23+0000 wait=999.965316ms ok=true  event=engine-reset-confirmed
    clsync.go:107:              DEBUG[12-19|04:21:22.403] CL sync received forkchoice update       role=sequencer unsafe=f27875..efed49:0 safe=f27875..efed49:0 finalized=f27875..efed49:0
    status.go:66:               DEBUG[12-19|04:21:22.403] Forkchoice update                        role=sequencer unsafe=f27875..efed49:0 safe=f27875..efed49:0 finalized=f27875..efed49:0
    sequencer.go:457:           DEBUG[12-19|04:21:22.403] Sequencer is processing forkchoice update role=sequencer unsafe=f27875..efed49:0 latest=000000..000000:0
    pipeline.go:214:            INFO [12-19|04:21:22.403] Rewinding derivation-pipeline L1 traversal to handle reset role=sequencer
    l1_traversal.go:93:         INFO [12-19|04:21:22.403] completed reset of derivation pipeline   role=sequencer origin=65615c..4c99cd:0
    pipeline.go:179:            DEBUG[12-19|04:21:22.403] reset of stage completed                 role=sequencer stage=0 origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.403] Sync process step                        role=sequencer
    l1_retrieval.go:83:         INFO [12-19|04:21:22.403] Reset of L1Retrieval done                role=sequencer origin=65615c..4c99cd:0
    pipeline.go:179:            DEBUG[12-19|04:21:22.403] reset of stage completed                 role=sequencer stage=1 origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.403] Sync process step                        role=sequencer
    pipeline.go:179:            DEBUG[12-19|04:21:22.403] reset of stage completed                 role=sequencer stage=2 origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.403] Sync process step                        role=sequencer
    pipeline.go:179:            DEBUG[12-19|04:21:22.403] reset of stage completed                 role=sequencer stage=3 origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.403] Sync process step                        role=sequencer
    channel_mux.go:43:          INFO [12-19|04:21:22.403] ChannelMux: activating pre-Holocene stage during reset role=sequencer origin=65615c..4c99cd:0
    pipeline.go:179:            DEBUG[12-19|04:21:22.403] reset of stage completed                 role=sequencer stage=4 origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.403] Sync process step                        role=sequencer
    pipeline.go:179:            DEBUG[12-19|04:21:22.403] reset of stage completed                 role=sequencer stage=5 origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.404] Sync process step                        role=sequencer
    batch_mux.go:39:            INFO [12-19|04:21:22.404] BatchMux: activating pre-Holocene stage during reset role=sequencer origin=65615c..4c99cd:0
    pipeline.go:179:            DEBUG[12-19|04:21:22.404] reset of stage completed                 role=sequencer stage=6 origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.404] Sync process step                        role=sequencer
    pipeline.go:179:            DEBUG[12-19|04:21:22.404] reset of stage completed                 role=sequencer stage=7 origin=65615c..4c99cd:0
    state.go:398:               DEBUG[12-19|04:21:22.404] Sync process step                        role=sequencer
    l1_retrieval.go:62:         DEBUG[12-19|04:21:22.404] fetching next piece of data              role=sequencer
    l1_traversal.go:64:         DEBUG[12-19|04:21:22.404] can't find next L1 block info (yet)      role=sequencer number=1 origin=65615c..4c99cd:0
    deriver.go:119:             DEBUG[12-19|04:21:22.404] Derivation process went idle             role=sequencer progress=65615c..4c99cd:0 err=EOF
    sequencer.go:366:           DEBUG[12-19|04:21:22.405] Sequencer action                         role=sequencer
    sequencer.go:532:           INFO [12-19|04:21:22.405] Started sequencing new block             role=sequencer parent=f27875..efed49:0 l1Origin=65615c..4c99cd:0
    sequencer.go:577:           DEBUG[12-19|04:21:22.405] prepared attributes for new block        role=sequencer num=1 time=1,734,582,076            origin=65615c..4c99cd:0 origin_time=1,734,582,075 noTxPool=false
    sequencer.go:166:           DEBUG[12-19|04:21:22.405] Sequencer action schedule changed        role=sequencer time=2024-12-19T04:21:23+0000 wait=997.725626ms ok=false event=sequencer-action
    clsync.go:107:              DEBUG[12-19|04:21:22.406] CL sync received forkchoice update       role=sequencer unsafe=f27875..efed49:0 safe=f27875..efed49:0 finalized=f27875..efed49:0
    status.go:66:               DEBUG[12-19|04:21:22.406] Forkchoice update                        role=sequencer unsafe=f27875..efed49:0 safe=f27875..efed49:0 finalized=f27875..efed49:0
    sequencer.go:457:           DEBUG[12-19|04:21:22.406] Sequencer is processing forkchoice update role=sequencer unsafe=f27875..efed49:0 latest=f27875..efed49:0
    sequencer.go:223:           DEBUG[12-19|04:21:22.406] Sequencer started building new block     role=sequencer payloadID=0x22210bf2bc2aee07 parent=f27875..efed49:0 parent_time=1,734,582,075
    sequencer.go:166:           DEBUG[12-19|04:21:22.406] Sequencer action schedule changed        role=sequencer time=2024-12-19T04:21:22+0000 wait=-240ns       ok=true  event=build-started
    dencun_fork_test.go:238: 
                Error Trace:    /var/lib/circleci-runner/workdir/op-e2e/actions/upgrades/dencun_fork_test.go:238
                Error:          An error is expected but got nil.
                Test:           TestDencunBlobTxInclusion
--- FAIL: TestDencunBlobTxInclusion (7.20s)
FAIL op-e2e/actions/upgrades.TestDencunBlobTxInclusion (7.20s)
PASS op-e2e/actions/proofs.Test_ProgramAction_HoloceneActivation/HonestClaim-HoloceneActivation-Granite (1.81s)
PASS op-e2e/actions/proofs.Test_ProgramAction_HoloceneActivation (0.00s)
PASS op-e2e/opgeth.TestInvalidDepositInFCU (3.70s)
PASS op-e2e/actions/helpers.TestCrossLayerUser_Standard/fork_regolith/not_yet (2.49s)
PASS op-e2e/system/bridge.TestMixedWithdrawalValidity_Standard/withdrawal_test#2 (47.76s)
=== RUN   TestDencunBlobTxRPC
=== PAUSE TestDencunBlobTxRPC
=== CONT  TestDencunBlobTxRPC
    e2e.go:104: Running test. Assigned executor (0) matches current executor (0) of total (1)
    dencun_fork_test.go:207: 
                Error Trace:    /var/lib/circleci-runner/workdir/op-e2e/actions/upgrades/dencun_fork_test.go:207
                Error:          An error is expected but got nil.
                Test:           TestDencunBlobTxRPC
--- FAIL: TestDencunBlobTxRPC (7.20s)
FAIL op-e2e/actions/upgrades.TestDencunBlobTxRPC (7.20s)
PASS op-e2e/actions/helpers.TestCrossLayerUser_Standard/fork_regolith/at_genesis (2.62s)
PASS op-e2e/actions/helpers.TestCrossLayerUser_Standard/fork_regolith/after_genesis (2.64s)
PASS op-e2e/actions/helpers.TestCrossLayerUser_Standard/fork_regolith (0.00s)
=== RUN   TestDencunBlobTxInTxPool
=== PAUSE TestDencunBlobTxInTxPool
=== CONT  TestDencunBlobTxInTxPool
    e2e.go:104: Running test. Assigned executor (0) matches current executor (0) of total (1)
    dencun_fork_test.go:220: 
                Error Trace:    /var/lib/circleci-runner/workdir/op-e2e/actions/upgrades/dencun_fork_test.go:220
                Error:          An error is expected but got nil.
                Test:           TestDencunBlobTxInTxPool
--- FAIL: TestDencunBlobTxInTxPool (7.39s)
FAIL op-e2e/actions/upgrades.TestDencunBlobTxInTxPool (7.39s)
```

### CODE REVIEW

**Comment by qzhodl** [comment]
Is this PR ready for review?

**Comment by qzhodl** [comment]
Does this e2e test utilize our fork of op-geth, or is it still relying on the upstream version?

**Comment by syntrust** [comment]
> Does this e2e test utilize our fork of op-geth, or is it still relying on the upstream version?

github.com/ethstorage/op-geth

**Review by qzhodl — APPROVED** [review]

**Review by blockchaindevsh — APPROVED** [review]
LGTM!

Btw, the tests here can be a good start for implementing  https://github.com/ethstorage/optimism/issues/102 .

**Review by pochenai — APPROVED** [review]

**Pull request merged**
